#!/usr/bin/env bash

# Load variables
source envsetup.sh

# Darknet Paths
DARKNET_STATIC_LIB_PATH=${DARKNET_PATH}
DARKNET_INCLUDE_PATH=${DARKNET_PATH}/include

# OpenCV Paths
OPENCV_STATIC_PATH=${OPENCV_INSTALL_PATH}

cmake . -DDARKNET_STATIC_LIB_PATH="${DARKNET_STATIC_LIB_PATH}" -DDARKNET_INCLUDE_PATH="${DARKNET_INCLUDE_PATH}" -DOPENCV_STATIC_PATH="${OPENCV_STATIC_PATH}" -DCMAKE_BUILD_TYPE="Release"

make
